### ISSUE TITLE
Checklist for public release of mitiq

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#268]
This is a checklist of tasks to do before the repository becomes public. Some are proposals of things that could be implemented or improved and should be discussed, possibly here if on github, take them as ideas:

Needed for Launch
- [x] check packaging tasks as per #230 
- [x] add syntax checks via [black](https://github.com/psf/black) (#279)
- [x] add `CHANGELOG.md`
- [x] spruce up the `README.md` (#330 )
- [x] enforce type hints via `mypy` (see also: #253)

Immediately after open-sourcing
- [x] add code coverage (coveralls not free for private repos)
- [x] trigger CI on all pushes (#316 )

-----------------------
Optional stuff:
- [ ] consider using docker for CI even beyond PyQuil (In a python-only environment this may be an overkill, but certainly it makes everything robust)
- [ ] have guides for contributors and maintainers  and possibly autoreleases to pypi, test pypi.
- [x] consider adding templates for PRs or issues: It would certainly help new contributors, may be cumbersome for UF team. In PRs, it could remind contributors to check code with [black](https://github.com/psf/black).=
- [x] update the mitiq roadmap on the wiki, see #266

**Comment by willzeng** [comment]
#316 checked a box here

**Comment by willzeng** [comment]
With #330 the needed parts for this issue are checked and so will close this issue
